name: projet-serre-serial
license: GPL-3.0
summary: Application de liaison série entre l'ordinateur (Raspberry PI) et l'Arduino
description: |
  **Dépendance (obligatoire) :**

    sudo snap install projet-serre-api

  **Activer hotplug :**

  Activez le support hotplug avec la commande suivante :

    sudo snap set system experimental.hotplug=true

  Redémarrer snapd :

    sudo systemctl restart snapd

  Connecter la carte Arduino Uno à Projet Serre Serial :

    sudo snap connect projet-serre-serial:serial-port :arduinouno

  Redémarrer le système :

    sudo systemctl reboot
base: core18
grade: stable
confinement: strict

adopt-info: projet-serre-serial

architectures:
  - build-on: arm64
  - build-on: armhf
  - build-on: amd64

apps:
  projet-serre-serial:
    command: usr/bin/python3 $SNAP/bin/projet-serre-serial
    daemon: simple
    restart-condition: always
    plugs: [home, serial-port, network, network-bind]

parts:
  projet-serre-serial:
    after: [setup]
    plugin: python
    python-version: python3
    source: https://github.com/anrouxel/projet-serre-serial.git
    source-type: git
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed 's/v//' | sed "s/-g/%/"  | cut -d "%" -f1)"
    build-packages:
      - git
      - sed

  setup:
    plugin: python
    python-version: python3
    python-packages: [pyserial, pip, requests]